title: OpenGlobe - Open data, open maps. 
description: A site for GIS lessons, data, and people. Even sites about maps enjoy getting lost in the wild every once in a while. 
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

